title: 张璞博客
author: 张璞
subtitle: welcome to my website!

url: "https://zhangpublog.github.io"
baseurl: "/"

footer_only_homepage: true
footer_url: "https://zhangpublog.github.io"
footer_text: "张璞博客 2021"

profile-picture: assets/profile.png
favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "关于"
   link: "about"
 - name: "下载"
   absolute-link: "https://pro-panda.github.io/resume.pdf"
